# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8293ab3e5f75c60878e01d9afb25413e5733cf0efdeb85cd812a624a3d3bf8257f4d7044a485a0a50b75b13aea62a65627c9f10ede6b2f076b0d4d82cc11588a

test:
  secret_key_base: 0bf50d68ad1794324f211cd86401dfc1aa999faad886b1c77b95b7a5ba2b1735ef7e089cd46e03f4af06cb34cb5721314443f05abfa213d6f87d285d9ca37470

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
